config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  resources :restaurants
  resources :users, :only => [:show, :new, :create, :edit, :update, :destroy]

end

app/models/reservations.rb
class Reservations < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/restaurants.rb
class Restaurant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	
	def index
		@restaurants = Restaurant.all
	end


	def show
		@restaurant = Restaurant.find(params[:id])
	end


	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def new
		@restaurant = Restaurant.new
	end
	

	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to restaurant_path(@restaurant)
		else
			render :new
		end
	end


	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update_attributes(restaurant_params)
			redirect_to restaurant_path(@restaurant)
		else
			render :edit
		end
	end


	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurant_path
	end


	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :location, :summary, :email, :capacity)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show      
    @user = User.find(params[:id])          #show is to show user profile
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to restaurants_url, :notice => "You are signed up for Seat Yourself. BOOM!"
      else
        render :new
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to restaurants_url
    else
      render :edit
    end
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :location %><br />
		<%= f.text_field :location %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :summary %><br />
		<%= f.text_field :summary %>
	</div>

	<div class="field">
		<%= f.label :capacity %><br />
		<%= f.text_field :capacity %>
	</div>

	<div class="field">
		<%= f.label :price_range %><br />
		<%= f.text_field :price_range %>
	</div>

	<div class="field">
		<%= f.label :menu %><br />
		<%= f.text_field :menu %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Yo' Place</h1>

<%= render 'form' %>

	<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Welcome to Seat Yourself!</h2>

app/views/restaurants/new.html.erb
<h1>Add Your Fab Place of Foodery and Fun</h2>

	<%= render 'form' %>

	<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h2>Show</h2>

<p>Congratulations! You've added your amazeballs restaurant! Way to go homeslice!</p>

<p>
	<%= @restaurant.name %>
	<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>